# Generated by Django 6.1 on 2026-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctorschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='doctorschedule',
            name='unique_doctor_schedule',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], default=0),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday'), name='unique_doctor_weekday'),
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='day',
        ),
    ]
