# Generated by Django 6.1 on 2026-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
