# Generated by Django 6.1 on 2026-08-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appointment_is_follow_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='review_allowed',
            new_name='is_rated',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_attendance',
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance',
            field=models.CharField(choices=[('UNKNOWN', 'لم يتم تحديد الحضور'), ('ATTENDED', 'حضر'), ('ABSENT', 'لم يحضر')], default='UNKNOWN', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUpAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_requests', to='accounts.doctor')),
                ('original_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_request', to='accounts.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
