# Generated by Django 6.1 on 2026-08-15 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_review_allowed_appointment_is_rated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attendance',
            field=models.CharField(choices=[('NOT_MARKED', 'لم يتم تحديد الحضور'), ('ATTENDED', 'حضر'), ('ABSENT', 'لم يحضر')], default='NOT_MARKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='followupappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_appointments', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='followupappointment',
            name='original_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_record', to='accounts.appointment'),
        ),
        migrations.AlterField(
            model_name='followupappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
