# Generated by Django 6.1 on 2026-08-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_appointment_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupappointment',
            name='original_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_records', to='accounts.appointment'),
        ),
    ]
